/run/numberOfThreads 44

/testhadr/phys/thermalScattering true

/run/initialize

/process/had/rdm/thresholdForVeryLongDecayTime 1.0e+60 year

/process/had/rdm/setRadioactiveDecayFile 98 252 ../decayfolder/z98.a252

/gun/particle neutron

/gun/energy 0.1 MeV
/run/beamOn 10000
/gun/energy 0.2 MeV
/run/beamOn 10000
/gun/energy 0.3 MeV
/run/beamOn 10000
/gun/energy 0.4 MeV
/run/beamOn 10000
/gun/energy 0.5 MeV
/run/beamOn 10000
/gun/energy 0.6 MeV
/run/beamOn 10000
/gun/energy 0.7 MeV
/run/beamOn 10000
/gun/energy 0.8 MeV
/run/beamOn 10000
/gun/energy 0.9 MeV
/run/beamOn 10000
/gun/energy 1 MeV
/run/beamOn 10000
/gun/energy 1.1 MeV
/run/beamOn 10000
/gun/energy 1.2 MeV
/run/beamOn 10000
/gun/energy 1.3 MeV
/run/beamOn 10000
/gun/energy 1.4 MeV
/run/beamOn 10000
/gun/energy 1.5 MeV
/run/beamOn 10000
/gun/energy 1.6 MeV
/run/beamOn 10000
/gun/energy 1.7 MeV
/run/beamOn 10000
/gun/energy 1.8 MeV
/run/beamOn 10000
/gun/energy 1.9 MeV
/run/beamOn 10000
/gun/energy 2 MeV
/run/beamOn 10000
/gun/energy 2.1 MeV
/run/beamOn 10000
/gun/energy 2.2 MeV
/run/beamOn 10000
/gun/energy 2.3 MeV
/run/beamOn 10000
/gun/energy 2.4 MeV
/run/beamOn 10000
/gun/energy 2.5 MeV
/run/beamOn 10000
/gun/energy 2.6 MeV
/run/beamOn 10000
/gun/energy 2.7 MeV
/run/beamOn 10000
/gun/energy 2.8 MeV
/run/beamOn 10000
/gun/energy 2.9 MeV
/run/beamOn 10000
/gun/energy 3 MeV
/run/beamOn 10000
/gun/energy 3.1 MeV
/run/beamOn 10000
/gun/energy 3.2 MeV
/run/beamOn 10000
/gun/energy 3.3 MeV
/run/beamOn 10000
/gun/energy 3.4 MeV
/run/beamOn 10000
/gun/energy 3.5 MeV
/run/beamOn 10000
/gun/energy 3.6 MeV
/run/beamOn 10000
/gun/energy 3.7 MeV
/run/beamOn 10000
/gun/energy 3.8 MeV
/run/beamOn 10000
/gun/energy 3.9 MeV
/run/beamOn 10000
/gun/energy 4 MeV
/run/beamOn 10000
/gun/energy 4.1 MeV
/run/beamOn 10000
/gun/energy 4.2 MeV
/run/beamOn 10000
/gun/energy 4.3 MeV
/run/beamOn 10000
/gun/energy 4.4 MeV
/run/beamOn 10000
/gun/energy 4.5 MeV
/run/beamOn 10000
/gun/energy 4.6 MeV
/run/beamOn 10000
/gun/energy 4.7 MeV
/run/beamOn 10000
/gun/energy 4.8 MeV
/run/beamOn 10000
/gun/energy 4.9 MeV
/run/beamOn 10000
/gun/energy 5 MeV
/run/beamOn 10000
/gun/energy 5.1 MeV
/run/beamOn 10000
/gun/energy 5.2 MeV
/run/beamOn 10000
/gun/energy 5.3 MeV
/run/beamOn 10000
/gun/energy 5.4 MeV
/run/beamOn 10000
/gun/energy 5.5 MeV
/run/beamOn 10000
/gun/energy 5.6 MeV
/run/beamOn 10000
/gun/energy 5.7 MeV
/run/beamOn 10000
/gun/energy 5.8 MeV
/run/beamOn 10000
/gun/energy 5.9 MeV
/run/beamOn 10000
/gun/energy 6 MeV
/run/beamOn 10000
/gun/energy 6.1 MeV
/run/beamOn 10000
/gun/energy 6.2 MeV
/run/beamOn 10000
/gun/energy 6.3 MeV
/run/beamOn 10000
/gun/energy 6.4 MeV
/run/beamOn 10000
/gun/energy 6.5 MeV
/run/beamOn 10000
/gun/energy 6.6 MeV
/run/beamOn 10000
/gun/energy 6.7 MeV
/run/beamOn 10000
/gun/energy 6.8 MeV
/run/beamOn 10000
/gun/energy 6.9 MeV
/run/beamOn 10000
/gun/energy 7 MeV
/run/beamOn 10000
/gun/energy 7.1 MeV
/run/beamOn 10000
/gun/energy 7.2 MeV
/run/beamOn 10000
/gun/energy 7.3 MeV
/run/beamOn 10000
/gun/energy 7.4 MeV
/run/beamOn 10000
/gun/energy 7.5 MeV
/run/beamOn 10000
/gun/energy 7.6 MeV
/run/beamOn 10000
/gun/energy 7.7 MeV
/run/beamOn 10000
/gun/energy 7.8 MeV
/run/beamOn 10000
/gun/energy 7.9 MeV
/run/beamOn 10000
/gun/energy 8 MeV
/run/beamOn 10000
/gun/energy 8.1 MeV
/run/beamOn 10000
/gun/energy 8.2 MeV
/run/beamOn 10000
/gun/energy 8.3 MeV
/run/beamOn 10000
/gun/energy 8.4 MeV
/run/beamOn 10000
/gun/energy 8.5 MeV
/run/beamOn 10000
/gun/energy 8.6 MeV
/run/beamOn 10000
/gun/energy 8.7 MeV
/run/beamOn 10000
/gun/energy 8.8 MeV
/run/beamOn 10000
/gun/energy 8.9 MeV
/run/beamOn 10000
/gun/energy 9 MeV
/run/beamOn 10000
/gun/energy 9.1 MeV
/run/beamOn 10000
/gun/energy 9.2 MeV
/run/beamOn 10000
/gun/energy 9.3 MeV
/run/beamOn 10000
/gun/energy 9.4 MeV
/run/beamOn 10000
/gun/energy 9.5 MeV
/run/beamOn 10000
/gun/energy 9.6 MeV
/run/beamOn 10000
/gun/energy 9.7 MeV
/run/beamOn 10000
/gun/energy 9.8 MeV
/run/beamOn 10000
/gun/energy 9.9 MeV
/run/beamOn 10000
/gun/energy 10 MeV
/run/beamOn 10000
